### ISSUE TITLE
 Doubts about sampling rate

### ISSUE THREAD

**Issue by 980202006** [yl4579/StarGANv2-VC#10]
I noticed that the torchaudio.transforms.MelSpectrogram you used is 16000 sampling rate, but the wav read is 24000 sampling rate. In other words, you use a mel with a sampling rate of 16,000 for audio with a sampling rate of 24,000 and use it as the target.Will this affect？

**Comment by yl4579** [comment]
It doesn't matter, because, in the end, the results are simply that you downsample the audio into 24 kHz, as setting sr = 16,000 means you map your audio into a range of 0 to 8 kHz. However, since ParallelWaveGAN is able to upsample, i.e. it can synthesize waveforms of higher sampling rate even if the input melspectrograms are of lower sampling rate, it barely has any effects in the generated audios.

**Comment by 980202006** [comment]
Thank you!

**Comment by 980202006** [comment]
Putting aside the vocoder, what does the sampling rate affect in the mel calculation? The 16000 sampling rate mel calculates the 24000 wav file, and whether the calculation result is the usable mel spectrum

**Comment by yl4579** [comment]
I think this will be helpful: [https://stackoverflow.com/questions/57053654/why-my-8khz-wav-files-mel-feature-extracted-differently-in-sr-16khz-and-44-1k](https://stackoverflow.com/questions/57053654/why-my-8khz-wav-files-mel-feature-extracted-differently-in-sr-16khz-and-44-1k)

**Comment by 980202006** [comment]
That's great. Thank you!

**Comment by iehppp2010** [comment]
> It doesn't matter, because, in the end, the results are simply that you downsample the audio into 16 kHz, as setting sr = 16,000 means you map your audio into a range of 0 to 8 kHz. However, since ParallelWaveGAN is able to upsample, i.e. it can synthesize waveforms of higher sampling rate even if the input melspectrograms are of lower sampling rate, it barely has any effects in the generated audios.

I want to know how you trained the ParallelWaveGAN vocoder model that you provided in the README link.
Is it trained with 16kHz audio melspectrograms, then synthesize 24KHz audio?

![image](https://user-images.githubusercontent.com/22955379/143564034-da5f990b-3070-4434-936b-a4dc23dd8140.png)

**Comment by yl4579** [comment]
@iehppp2010 No, the STFT was done with 24 kHz audio and mel-scale was done with a 16 kHz scale. See #8 for preprocessing.

**Comment by magicse** [comment]
Hi @980202006 
HiFi Gan was trained as 16Khz mels (24Khz audio with incorrect sr 16Khz) -> 24 Khz wav and it work something like as fake upsampler.
Therefore, now we have to give 24Khz audio for calculation of the mel spectrogram as 16Khz without real resampling.

I think it was a mistake when training the HiFi Gan model (torchaudio.transforms.MelSpectrogram set by default sr = 16Khz). And now it's baked into the pipeline. The correct way is of course that the mel spectrograms should be calculated from 24Khz with real sr 24Khz and after passing through HiFi Gan give 24Khz wave.
To avoid this situation you need retrain all models ASR, JDC and HiFi-Gan with correct mels. Force set sample_rate=24000

```
to_mel = torchaudio.transforms.MelSpectrogram(
    sample_rate=24000,
    n_fft=2048,
    win_length=1200,
    hop_length=300,
    n_mels=80,
)
```
