### ISSUE TITLE
How to inference with unseen speakers?

### ISSUE THREAD

**Issue by Charlottecuc** [yl4579/StarGANv2-VC#13]
Hi. The work is amazing. I notice that the inference.py file only support many-to-many conversion. Could you tell me how to modify it to any-to-many conversion and also singing voice conversion? 
Thank you very much.

**Comment by skol101** [comment]
Yep, this work is really good.
I'm also interested in any-to-many conversion as shown on the examples provided on the demo page. So, basically, I take the input wav from an unseen speaker, choose target from the pretrained/finetuned model and make conversion as in demo notebok?
