### ISSUE TITLE
any tips on own dataset? say chinese content to japanese styel?

### ISSUE THREAD

**Issue by dragen1860** [yl4579/StarGANv2-VC#17]
Dear all:
  I was suprised by the voice conversion performance. Currently i would like to play with some cross language conversion, let's say: source chinese -> target japanese style. anyone give some advise. such as how many non-parallel data should be fine and will it acheieve good or great performance like the many-to-many setting? thank you very much.

**Comment by yl4579** [comment]
In my experience, 10 speakers with around 20 mins for each speaker is enough to produce reasonably good results. I haven't tried with a number of speakers less than 10, but for some speakers, the data can be as low as 5 mins and it makes almost no difference. If the number of speakers is large, however, the discriminator may fail to capture speaker-specific characteristics, so I would say 10-20 speakers would be the best setting.
