### ISSUE TITLE
remove mapping network in training stage

### ISSUE THREAD

**Issue by dragen1860** [yl4579/StarGANv2-VC#19]
Dear all
  I wonder what if i remove the mapping network and only take style vector `s` from `ref`. any one give some tips or did some experiments? thank you.

**Comment by yl4579** [comment]
[@980202006](https://github.com/yl4579/StarGANv2-VC/issues/6) has done it, you may comment on that issue. It is as simple as removing the lines that train with the mapping network and removing the style diversification loss to prevent loss divergence.
