### ISSUE TITLE
Should I re-train ParallelWaveGan

### ISSUE THREAD

**Issue by kikirizki** [yl4579/StarGANv2-VC#23]
Hi thank you for your great work, I intended to train to a language other than english, should I re-train the vocoder to the exact same dataset I use, or is it will be good enough if I use ParallelWaveGan that already trained to the language I want but with different dataset? . What about the ParallelWaveGan in this repo demo did you retrain to" the 20 VCTK speakers"? thank you in advance

**Comment by yl4579** [comment]
I'm sorry for the very late reply because I was very busy at the end of the year. You don't need to retrain anything for the new language, because all of these settings are pretty much language independent. You only need to fine-tune the model for the new language you are working on
