### ISSUE TITLE
Is it possible to keep the timbre the same and only change the pitch

### ISSUE THREAD

**Issue by 980202006** [yl4579/StarGANv2-VC#29]
I tried your pitchshift code but it changes the timbre, is there a way, only changing the pitch doesn't change the timbre？

**Comment by yl4579** [comment]
That pitch shift is more like a formant shift than actual pitch shift. For an actual pitch shift, you may need to do it in the time domain. Please try [audiomentations](https://github.com/iver56/audiomentations).
