### ISSUE TITLE
Training questions: samples and resuming

### ISSUE THREAD

**Issue by skol101** [yl4579/StarGANv2-VC#31]
I've started training and have questions:
1. I can see train/eval phases, but no wav samples in the log_dir
2. Can training be resumed from ? I assume it can if I put "epoch_xxx.pth" in the config file ?

**Comment by yl4579** [comment]
1. There is no waveform generated in the training and evaluation process, so you will need to do it yourself with a vocoder.
2. Yes, just edit the `pretrained_model` field in the config file.
