### ISSUE TITLE
Duration is ~10% shorter that original

### ISSUE THREAD

**Issue by skol101** [yl4579/StarGANv2-VC#37]
Is this because of vocoder (in this examples I've used StyleMelgan) the generated audio duration is about 10% shorter than original? 
Update: I've tried with Hifigan and the result is also shorter than the original.
Is this expected? 
![Screenshot from 2022-02-20 16-14-39](https://user-images.githubusercontent.com/53978091/154847044-2f043006-2ada-4f94-8500-c94bbbfd7c0d.png)

**Comment by yl4579** [comment]
Please avoid posting issues that are irrelevant to this repo in the future. These problems should be addressed in their corresponding repos like StyleMelgan and HifiGAN. Thank you for your understanding.
