### ISSUE TITLE
how to change pitch

### ISSUE THREAD

**Issue by MMMMichaelzhang** [yl4579/StarGANv2-VC#40]
Hi，thanks for this project.It is amazing.When I was thinking about converting between male and female voices, I didn't know how to tune the pitch. Now I'm changing the male voice to a female voice, and the pitch is too high. Can you tell me where to adjust it? Thank you very much.

**Comment by yl4579** [comment]
The pitch can be lowered by using a reference with a lower pitch. If you use the mapping network, however, the pitch is uncontrollable.

**Comment by MMMMichaelzhang** [comment]
Thank you for your reply。Do you mean I should lower the input audio pitch before converting it? I tried using librosa to lower the input audio pitch first, then the audio becomes a little weird. @yl4579

**Comment by mraj96** [comment]
> The pitch can be lowered by using a reference with a lower pitch. If you use the mapping network, however, the pitch is uncontrollable.

When I use the style encoder network, target speaker similarity is decreasing. How to tackle pitch and speaker information both in style encode?
