### ISSUE TITLE
Update style encoder after deleting mapping network

### ISSUE THREAD

**Issue by Charlottecuc** [yl4579/StarGANv2-VC#46]
Hi. I notice that the style encoder is optimized together with the mapping network (e.g. https://github.com/yl4579/StarGANv2-VC/issues/14#issuecomment-949078211). If the original mapping network is deleted, should the style encoder be optimized with  the generator?

**Comment by yl4579** [comment]
You may want to discuss it with [@98020200](https://github.com/980202006)

**Comment by skol101** [comment]
@Charlottecuc good question, how have you managed this issue?
I have simply did this
```python
  self.optimizer.step('generator', scaler=scaler)
            self.optimizer.step('style_encoder', scaler=scaler)
```
