### ISSUE TITLE
How much loss model will converge？

### ISSUE THREAD

**Issue by 980202006** [yl4579/StarGANv2-VC#5]
hi, I want to train a new model using mixed open source data. I would like to know,
How much loss model will converge
And the required gpu resources and time-consuming

**Comment by yl4579** [comment]
You may want to train with the provided data and config first and figure it out yourself because it varies between machines and configurations.

**Comment by 980202006** [comment]
If I just want to reproduce the training, use the data and model structure given in the example，How much loss model will converge？

**Comment by yl4579** [comment]
As with training other GAN models, it is difficult to tell when the model has converged. You will need to inspect the generated samples regularly and pick the checkpoint that produces the best samples. Loss values are not very interpretable for GAN training, unfortunately, but the cycle consistency loss can be used as an indicator for stopping training. If you see no significant decrease in cycle consistent loss in the validation set, it's probably time to stop.

**Comment by 980202006** [comment]
Perfect answer！This is too helpful for practice.
