### ISSUE TITLE
ASR training data must be same with stargan training data?

### ISSUE THREAD

**Issue by joan126** [yl4579/StarGANv2-VC#52]
Hi, I am trying to training starganv2 vc ,   one question about dataset for training ASR and vc,  can I use different dataset for ASR training and starggan ?

**Comment by yl4579** [comment]
It can be totally different, even in different languages. The released pre-trained model was trained on LibriTTS and the voice conversion model was trained on VCTK.

**Comment by joan126** [comment]
> It can be totally different, even in different languages. The released pre-trained model was trained on LibriTTS and the voice conversion model was trained on VCTK. The same ASR model works for JVS datset (Japanese) too.

I am working on Mandarin Chinese.  will the pretrained ASR model works for this?

**Comment by yl4579** [comment]
I haven't tested on Mandarin yet, but I think it should, though the quality would not be as good as if you train it directly with Mandarin. You can refer to this issue for ASR training and data preparation in Mandarin: https://github.com/yl4579/AuxiliaryASR/issues/2

**Comment by joan126** [comment]
> I haven't tested on Mandarin yet, but I think it should, though the quality would not be as good as if you train it directly with Mandarin. You can refer to this issue for ASR training and data preparation in Mandarin: [yl4579/AuxiliaryASR#2](https://github.com/yl4579/AuxiliaryASR/issues/2)

thanks a lot!!
