### ISSUE TITLE
F0 model training on 160 mels

### ISSUE THREAD

**Issue by ashfaquekhalid** [yl4579/StarGANv2-VC#55]
<img width="1425" alt="Screenshot 2022-06-27 at 6 04 17 PM" src="https://user-images.githubusercontent.com/58369934/175943020-9b0c5074-a36f-4630-b649-cfecd065101c.png">

I am training the F0 model on 160 mels with the pre-trained f0 model that you provided as a base model. training data is Librispeech-clean-100. is the model overfitting only in 10-20 epochs?

**Comment by ashfaquekhalid** [comment]
fixed

**Comment by superhg** [comment]
> 

could you share your solution to this overfiting issue? I met same issue

**Comment by MMMMichaelzhang** [comment]
@ashfaquekhalid I met same issue

**Comment by joan126** [comment]
@yl4579 could you help to see this issue?

**Comment by yl4579** [comment]
@joan126 @MMMMichaelzhang @superhg see https://github.com/yl4579/PitchExtractor/issues/4
