### ISSUE TITLE
Meldataset.py MEL_PARAMS question

### ISSUE THREAD

**Issue by skol101** [yl4579/StarGANv2-VC#56]
Is this done on purpose where MEL_PARAMS don't  include sample_rate, thus default rate of 16000 will be used used?

https://github.com/yl4579/StarGANv2-VC/blob/c17b458ed803792e270f5d8d3c038155404d04e7/meldataset.py#L29
 
https://github.com/yl4579/StarGANv2-VC/blob/c17b458ed803792e270f5d8d3c038155404d04e7/meldataset.py#L50

**Comment by Owen-Fish** [comment]
sample_rate used in torchaudio.transforms.MelSpectrogram(**kwargs) are used to calculate the bin of filter banks. Only filter bin's resolution are influenced  by changing this parameter.

**Comment by magicse** [comment]
Hi @skol101 
https://github.com/yl4579/StyleTTS/issues/74#issuecomment-3148500108

Yes, sample_rate affects the calculation of filters (mel scale), but not the signal itself.
If you feed audio sampled at 24 kHz, but MelSpectrogram thinks it's 16 kHz — the result will be physically incorrect.
Mel filters will be calculated as if the maximum frequency is 8 kHz.
And real audio contains components up to 12 kHz.
As a result, high frequencies will either be lost or "wrongly fit" into low mel channels.
And if you feed a signal with a physically different sample_rate (24kHz, not 16kHz), the spectrograms will be mathematically incorrect.
If HiFi-GAN is trained on the same "erroneous" mel-spectrograms, it will work on a "distorted feature space".
Sample_rate  must match the real sample_rate of the signal for a correct mel spectrogram.

To avoid this situation you need retrain all models ASR, JDC and HiFi-Gan with correct mels. Force set sample_rate=24000
```
to_mel = torchaudio.transforms.MelSpectrogram(
    sample_rate=24000,
    n_fft=2048,
    win_length=1200,
    hop_length=300,
    n_mels=80,
)
```
