### ISSUE TITLE
Error during training

### ISSUE THREAD

**Issue by CrackerHax** [yl4579/StarGANv2-VC#58]
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1346}
{'max_lr': 2e-06, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1346}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1346}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1346}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1346}
{'max_lr': 0.0001, 'pct_start': 0.0, 'epochs': 150, 'steps_per_epoch': 1346}
[train]: 100%|█████████████████████████████████████████████████████████| 1346/1346 [15:04<00:00,  1.49it/s]
[eval]:  99%|█████████████████████████████████████████████████████████████▎| 92/93 [00:31<00:00,  2.88it/s]
Traceback (most recent call last):
  File "train.py", line 156, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 126, in main
    eval_results = trainer._eval_epoch()
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/e/ai/src/StarGANv2-VC/trainer.py", line 255, in _eval_epoch
    g_loss, g_losses_latent = compute_g_loss(
  File "/mnt/e/ai/src/StarGANv2-VC/losses.py", line 106, in compute_g_loss
    loss_f0 = f0_loss(F0_fake, F0_real)
  File "/mnt/e/ai/src/StarGANv2-VC/losses.py", line 212, in f0_loss
    x_mean = compute_mean_f0(x_f0)
  File "/mnt/e/ai/src/StarGANv2-VC/losses.py", line 203, in compute_mean_f0
    f0_mean = f0_mean.expand(f0.shape[-1], f0_mean.shape[0]).transpose(0, 1) # (B, M)
IndexError: tuple index out of range

**Comment by CrackerHax** [comment]
Fixed this. Not sure what I did but maybe my file list was wrong, the samples were the wrong sampling rate or my batch size/epocs settings were causing it.

**Comment by aidiary** [comment]
I too encountered this problem when using the original corpus.
This problem occurs when the last evaluation batch is only one data.

`batch_size = 5`

```
[eval]:  96%|████████████████████████████████████████████████████▉  | 50/52 [00:21<00:00,  2.51it/s]
torch.Size([5, 192])
torch.Size([5, 192])
torch.Size([5, 192])
torch.Size([5, 192])
torch.Size([5, 192])
torch.Size([5, 192])
[eval]:  98%|█████████████████████████████████████████████████████▉ | 51/52 [00:22<00:00,  2.51it/s]
torch.Size([192])   <==
torch.Size([192])   <==
[eval]:  98%|█████████████████████████████████████████████████████▉ | 51/52 [00:23<00:00,  2.13it/s]
```

Fixed by setting DataLoader to `drop_last=True`
```
    data_loader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=(not validation),
        num_workers=num_workers,
        drop_last=True,
        collate_fn=collate_fn,
        pin_memory=(device != "cpu"),
    )
```

**Comment by yl4579** [comment]
Fixed this problem in the repo.
