### ISSUE TITLE
Seems to be incompatible with the colab environment

### ISSUE THREAD

**Issue by KJZH001** [yl4579/StarGANv2-VC#63]
Hello! It's great to have such an interesting and great project open source, I've read some articles and would like to try to train a model myself!

This is probably a pretty simple problem to solve, but I'm not very familiar with python and this is my first attempt at it, so I'm hoping for some help!

I followed the readme on Colab and everything seems to be working fine, but I'm stuck here

```python train.py --config_path ./Configs/config.yml```

To reduce the probability of errors, I currently chose to reproduce your VCTK model (step 4 in Pre-requisites)

After running '!python train.py --config_path . /Configs/config.yml' 

returned the following error
```
[libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
```

How can I solve this problem? Thank you!

**Comment by Francis-Komizu** [comment]
> Hello! It's great to have such an interesting and great project open source, I've read some articles and would like to try to train a model myself!
> 
> This is probably a pretty simple problem to solve, but I'm not very familiar with python and this is my first attempt at it, so I'm hoping for some help!
> 
> I followed the readme on Colab and everything seems to be working fine, but I'm stuck here
> 
> `python train.py --config_path ./Configs/config.yml`
> 
> To reduce the probability of errors, I currently chose to reproduce your VCTK model (step 4 in Pre-requisites)
> 
> After running '!python train.py --config_path . /Configs/config.yml'
> 
> returned the following error
> 
> ```
> [libprotobuf FATAL google/protobuf/stubs/common.cc:87] This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
> terminate called after throwing an instance of 'google::protobuf::FatalException'
>   what():  This program was compiled against version 3.9.2 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.17.3).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "bazel-out/k8-opt/bin/tensorflow/core/framework/tensor_shape.pb.cc".)
> ```
> 
> How can I solve this problem? Thank you!

Hello! Seems that this is a problem with google. In my case, I add the following codes during set-up and everything works...
```
!pip uninstall protobuf -y
!pip install --no-binary protobuf protobuf
```

**Comment by KJZH001** [comment]
> 
> Hello! Seems that this is a problem with google. In my case, I add the following codes during set-up and everything works...
> 
> ```
> !pip uninstall protobuf -y
> !pip install --no-binary protobuf protobuf
> ```

Thank you.I will find time to try it as soon as possible.
