### ISSUE TITLE
the role of original(vocoder) in the inference.ipynb?

### ISSUE THREAD

**Issue by rmaster520** [yl4579/StarGANv2-VC#64]
Hello! It's great to have such an interesting and great project open source.  However, this is my first time I've seen the operation of showing the "original(vocoder)" ,which is in the inference.ipynb.
Do you want to  evaluate the effect of the vocoder,compare it with other converted voices, or do you have other purposes for the source  speech processed with the vocoder(which is written as "original(vocoder)")  in the inference.ipynb?

**Comment by yl4579** [comment]
Yes, it was to compare the results from the vocoder reconstruction to identify whether the sound quality problem comes from the voice conversion model or the vocoder.
