### ISSUE TITLE
Training problems

### ISSUE THREAD

**Issue by MMMMichaelzhang** [yl4579/StarGANv2-VC#66]
![Screenshot from 2022-12-02 16-55-46](https://user-images.githubusercontent.com/91544231/205255246-03d533b2-5bef-41b6-8a53-8212eeb70f99.png)
The image is my eval data,the eval/asr seems overfit after 60 epoches,what should i do?Should i change the g_loss/lambda_asr?
Thank you very much.

**Comment by MMMMichaelzhang** [comment]
Is the bigger number of train/reg  the better?

**Comment by yl4579** [comment]
Not sure what you meant. It could be due to insufficient data, imbalanced lambda_asr, and so on. It is difficult to pinpoint the problem without more information.
