### ISSUE TITLE
Support needed for Teacher Forcing HiFiGAN Vocoder Finetuning

### ISSUE THREAD

**Issue by MuruganR96** [yl4579/StarGANv2-VC#69]
@yl4579 Thank you so much for this wonderful work

Support needed for Teacher Forcing HiFiGAN Vocoder Finetuning. Couldn't training converted Mel spectrogram as input to HiFiGAN fine-tuning.

Thanks

**Comment by yl4579** [comment]
For vocoder fine-tuning, you may want to fine-tune the vocoder to match the second-time converted samples (cycle-consistent samples) with the ground truth. The converted samples do not have ground truth so it cannot be fine-tuned.
