### ISSUE TITLE
Are there any details about the  neutral to emotional conversion？

### ISSUE THREAD

**Issue by 980202006** [yl4579/StarGANv2-VC#7]
Hello, on the sample page, I saw the audio from Neutral for emotional, and was surprised by this effect because it did two things: emotion conversion and voice conversion. Are two style encoders used? And whether there are any changes in training and model structure compared to the original model？

**Comment by yl4579** [comment]
It uses the exact same architecture but is trained on a different dataset. You simply need to change the dataset and will get emotion conversion for free, as training is completely unsupervised. The emotions or styles are learned automatically.

**Comment by 980202006** [comment]
What an excellent discriminator design, thank you!

**Comment by psvlnandu** [comment]
> It uses the exact same architecture but is trained on a different dataset. You simply need to change the dataset and will get emotion conversion for free, as training is completely unsupervised. The emotions or styles are learned automatically.

Hi, Did you train model for Emotional conversion? or are you using the pre trained model only?
