### ISSUE TITLE
Pre-computed style vectors

### ISSUE THREAD

**Issue by carlosfranzreb** [yl4579/StarGANv2-VC#75]
Hello,

I would like to use the best possible style vectors. Do you have the ones you used for the demo and paper? If not, how can I obtain them? Thank you for the great work!

**Comment by yl4579** [comment]
I used randomly chosen style vectors for demo and paper because there is basically no difference in terms of styles for VCTK dataset. You can use the styles sampled from mapper network as the "average" styles for a particular speaker.

**Comment by carlosfranzreb** [comment]
Alright, thank you!
