### ISSUE TITLE
cannot reproduce converted audio in demo examples

### ISSUE THREAD

**Issue by cwhstcnn** [yl4579/StarGANv2-VC#78]
hello, i try to inference with the sample audio provided in your website(https://starganv2-vc.github.io/), but cannot reproduce the converted audio as you did.  And I use the pretrained-model you provided in the repo.

pretrained-model:
1, Model.zip : https://drive.google.com/file/d/1nzTyyl-9A1Hmqya2Q_f2bpZkUoRjbZsY/view
2, Vocoder : https://drive.google.com/file/d/1q8oSAzwkqi99oOGXDZyLypCiz0Qzn3Ab/view

Mandarin source audio:
      https://raw.githubusercontent.com/starganv2-vc/starganv2-vc.github.io/main/wav/VCTK/Crosslingual/Mandarin/source.wav
Mandarin target audio:
      https://raw.githubusercontent.com/starganv2-vc/starganv2-vc.github.io/main/wav/VCTK/Crosslingual/Mandarin/target.wav

but my converted audio is quite different from yours:
     yours:
         https://raw.githubusercontent.com/starganv2-vc/starganv2-vc.github.io/main/wav/VCTK/Crosslingual/Mandarin/p254.wav
     mine:
         
[step0_p0.wav.zip](https://github.com/yl4579/StarGANv2-VC/files/10811089/step0_p0.wav.zip)

**Comment by cwhstcnn** [comment]
my converted audio:

**Comment by pybbvcf** [comment]
> it's my mistake that modify the speakers=[], sorry about that

Hi, I also encountered same error with you. May I ask how did you solve this? Thanks.
