### ISSUE TITLE
What was the pytorch version this model used for training? 

### ISSUE THREAD

**Issue by yurong58** [yl4579/StarGANv2-VC#79]
Hi! thank you for providing all these works! I really appreciate it. I am a beginner and had done training the model, however, I encounter a problem when doing the interference. 
![Screenshot from 2023-03-02 18-19-33](https://user-images.githubusercontent.com/126771050/222400651-0bc59418-df1e-4f8e-8a12-7120db010427.png)
According to the internet, it said that the pytorch version used for training the model isn't the same one I am using right now. I have looked through the information you have provided but still cant find anything about it. Do I miss anything? Thank you so much!!!

**Comment by daozhi0921** [comment]
按照如下环境安装， 测试可用， 你可以试试：
 librosa==0.7.2
 SoundFile
 munch
 pydub 
 pyyaml 
 click
 tensorboard==2.12.0
 numba==0.48.0
 pip install setuptools==56.1.0
pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
