### ISSUE TITLE
Compatibility with custom vocoder checkpoints?

### ISSUE THREAD

**Issue by Kreevoz** [yl4579/StarGANv2-VC#8]
Greetings!

I've tried to replace your supplied pretrained ParallelWaveGAN checkpoint with a different one I trained (Using the implementation over at https://github.com/kan-bayashi/ParallelWaveGAN ), to go along with a custom StarGANv2-VC checkpoint. 

I copied the parameters from the config.yml that you supply with your pretrained checkpoint exactly, and used your checkpoint for finetuning.

However, the resulting vocoder checkpoint cannot use the output of StarGANv2-VC correctly - it produces near-clipping, way too low-frequency-centric output, even when running over the original wave files for testing. 

After some investigation (and a lot of headache), it seems that the mel spectrograms produced by StarGANv2-VC use a different log base and are not compatible. So I trained a PWG vocoder with _log()_ instead of the default _log10()_, but this also did not yield acceptable results. 

It seems that the normalization you use for StarGANv2-VC is different, also. (?)
Your own vocoder checkpoint was trained with those changes implemented, since it works fine out of the box. But they're not documented.

If possible, **could you please share details about what changes you made when training your ParallelWaveGAN checkpoint**, so that other vocoder checkpoints may be correctly trained for use with StarGANv2-VC? That would be great.

**Comment by yl4579** [comment]
Please read the **ASR & F0 Models** section:

>The pretrained F0 and ASR models are provided under the `Utils` folder. Both the F0 and ASR models are trained with melspectrograms preprocessed using [meldataset.py](https://github.com/yl4579/StarGANv2-VC/blob/main/meldataset.py), and both models are trained on speech data only. 

> The ASR model is trained on English corpus, but it appears to work when training StarGANv2 models in other languages such as Japanese. The F0 model also appears to work with singing data. For the best performance, however, training your own ASR and F0 models is encouraged for non-English and non-speech data. 

> **You can edit the [meldataset.py](https://github.com/yl4579/StarGANv2-VC/blob/main/meldataset.py) with your own melspectrogram preprocessing, but the provided pretrained models will no longer work.** You will need to train your own ASR and F0 models with the new preprocessing. You may refer to repo [Diamondfan/CTC_pytorch](https://github.com/Diamondfan/CTC_pytorch) and [keums/melodyExtraction_JDC](https://github.com/keums/melodyExtraction_JDC) to train your own the ASR and F0 models, for example.

**Comment by Kreevoz** [comment]
I replaced the preprocessing and normalization code bits in the ParallelWaveGAN repo with the ones you pointed at, but I'm getting nowhere. 

Unlike your nicely structured StarGANv2-VC repo, the PWG code is neither compact nor easy to understand and I'm severely out of my league trying to make the code edits work together with the rest of the implementation because bits of it are scattered across way too many files. 

The PWG dataset preparation fails at the compute-statistics stage with:
`ValueError: X has 406 features, but StandardScaler is expecting 458 features as input. `

May be my fault. Actually most likely _is_ my fault. I don't know if I'm passing it data in the right way.
I understand why it needs those statistics but I don't understand how to fix it up so it tolerates the different preprocessing. 

Do you know if there is any fork/repo out there that has the necessary changes implemented already? Does not have to be clean code.

**Comment by yl4579** [comment]
The first thing you will need to do is to make sure the `hop_size`, `win_length`, and`` `sample_rate` are set correctly in the configuration files of ParallelWaveGAN because the size mismatch is most likely caused by those setting issues (i.e. sampling rate not divisible by hop size). Then you need to modify [line 213 in parallel_wavegan/bin/preprocess.py] (https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/parallel_wavegan/bin/preprocess.py#L213) to replace `logmelfilterbank` with the `preprocess` function above. You also need to make sure that [normalize.py] (https://github.com/kan-bayashi/ParallelWaveGAN/blob/master/parallel_wavegan/bin/normalize.py) does nothing because I didn't use the speaker statistics when training the vocoder as it appears to be unnecessary. 

Unfortuantely, I moved on from ParallelWaveGAN to HifiGAN because as you said the repo is very messy and hard to maintain,  so I didn't save the training code where I've made the change.

**Comment by Kreevoz** [comment]
Oh hm... HifiGAN I'm more familiar with, also. Grafting the normalization from your repo into it shouldn't be as hard as with PWG, though that raises the question in my mind if that'll have further repercussions. 

Since tacotron2 is involved in the teacher-forcing part of dataset preparation (for fine-tuning, which is the only feasible route given I mostly have small datasets to work with), that would mean I'd have to retrain a model for that as well, due to the replaced preprocessing + normalization?

And so I'd need to have full-fledged datasets, which is kinda throwing a wrench into the huge benefit of StarGANv2-VC, namely that it works with unannotated data and thus opens up interesting possibilities for playing around with voices one would normally not be able to build tts models for...

So I'm curious how you're using it.

**Comment by yl4579** [comment]
Why would you need to use tacotron 2 in this case? HifiGAN does not need any labels to train either, because it is just a vocoder.

**Comment by Kreevoz** [comment]
True, though the datasets I have are truly tiny and don't succeed when training from scratch. So far I've had success when using teacher-forcing when processing them, and for that I need tacotron2 parent models. Which were also finetuned. Maybe that explains my worry. 

Unless there is a way I'm not aware of -- feel free to tell me my approach is unnecessarily complex. I'd be delighted to just run across a vocoder for once that doesn't involve esotheric procedures for training and is easy to use.

**Comment by Kreevoz** [comment]
I finally got ParallelWaveGAN to accept the new preprocessing and produce a vocoder checkpoint that works with the other parts of your repo. 😤 Used your checkpoint for finetuning. I kept the speaker statistics.
Thank you very much for pointing me in the right direction.

**Comment by skol101** [comment]
@Kreevoz , how did you manage to achieve that -- i.e. changed PWGan code to accept new preprocessing ? I was finetuning StyleMelGan from the PWGan repo, but had the same issue as you -- vocoder checkpoint from Demo notebook just produce distorted sound. 

So I understand that your took PWGan checkpoint from this repo and continued training? I guess in my case I'd had to start from the start.
