### ISSUE TITLE
F0 models training and use

### ISSUE THREAD

**Issue by daozhi0921** [yl4579/StarGANv2-VC#80]
Hello, I have a question to ask. According to the F0 models training project you mentioned, after the training, put the model under the corresponding Utils/JDC, the model loading does not match, print the model parameters to see, the newly trained one The f0 model is inconsistent with the training model and parameters provided by you, so how to use it? Thanks!

**Comment by yl4579** [comment]
You just need to change `['net']` to `['model']` for the parameter keys.
