### ISSUE TITLE
TypeError: guvectorize() missing 1 required positional argument: 'signature'

### ISSUE THREAD

**Issue by yurong58** [yl4579/StarGANv2-VC#81]
Hi, I face another problem when running the inference.py. The error is: TypeError: guvectorize() missing 1 required positional argument: 'signature', and the picture is provided below. According to the internet it said I am missing parameters in numba, but I still have no idea how to deal with it. How can I solve it? Thanks a lot!!!  
![image](https://user-images.githubusercontent.com/126771050/225226474-effc9c9e-bc37-41fe-9aec-e0137c63697d.png)

**Comment by yl4579** [comment]
It is likely a version issue. You can refer to #79 for the right versions of different packages. For example, use the following packages suggested by @daozhi0921 

```
librosa==0.7.2
SoundFile
munch
pydub
pyyaml
click
tensorboard==2.12.0
numba==0.48.0
pip install setuptools==56.1.0
pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f
```

**Comment by yurong58** [comment]
Hi, thank you for your suggestions!! I have checked my versions which are all the same as the packages you provided. However, I still face the same problem, is there any other way I could solve it?

**Comment by yl4579** [comment]
Then it is a problem with your system. It seems like something is wrong with your librosa package, which is out of the scope of this repo. You may have to ask it in the librosa repo, or even ask ChatGPT for the solution.
