### ISSUE TITLE
How can I adjust the tensor shape for different data?

### ISSUE THREAD

**Issue by Golesheed** [yl4579/StarGANv2-VC#84]
Hello all,
I am trying to implement this repo for a data augmentation task. I want to convert every adult into an elderly voice to increase my elderly data as I will be doing an ASR on it.
I am using the Frisian common voice dataset (I have imported it via hugging face). But I am encountering TensorFlow issues (regarding the shape of my data and the shape of the tensor) which I don't know how to fix. Can anyone help?

[error.txt](https://github.com/yl4579/StarGANv2-VC/files/11351888/error.txt)

**Comment by yl4579** [comment]
You should first convert your waveform data into melspectrograms. See [meldataset.py](https://github.com/yl4579/StarGANv2-VC/blob/main/meldataset.py) for more details.
