### ISSUE TITLE
hi 一起讨论一下输出loss逐渐变成nan值情况的改进策略Let's discuss the improvement strategy for the situation where output loss gradually changes to nan value together

### ISSUE THREAD

**Issue by love112358** [yl4579/StarGANv2-VC#90]
大家好！这是我使用自己采集音频数据训练的结果，刚开始的loss值并不是nan，最后，当训练到120个epoch时，loss值变成nan值
Hello everyone! This is the result of training using audio data that I collected myself. Initially, the loss value was not NaN, but eventually, when training reached 120 epochs, the loss value became NaN.
epoch=122
![image](https://github.com/yl4579/StarGANv2-VC/assets/33959491/984d0040-c2f4-42d1-ada2-fb968475566c)
epoch=123
![image](https://github.com/yl4579/StarGANv2-VC/assets/33959491/4f767be1-0902-42f8-a4a0-931e5216dbf5)
epoch=149
![image](https://github.com/yl4579/StarGANv2-VC/assets/33959491/58a600ef-c12f-477e-bb56-6a0453b87f72)
这是tensorboard的显示结果
This is the display result from TensorBoard.
![image](https://github.com/yl4579/StarGANv2-VC/assets/33959491/4be4507d-9477-4e94-9cb2-afc9d118281b)
希望大家给我一下赶紧的建议
I hope everyone can give me some urgent advice.

**Comment by yl4579** [comment]
see https://github.com/yl4579/StarGANv2-VC/issues/60
