### ISSUE TITLE
Regarding Non-speech Vocal data in a dataset

### ISSUE THREAD

**Issue by SoshyHayami** [yl4579/StarGANv2-VC#92]
I was wondering if I could include laughing, sobbing and crying sounds of each person in the dataset, is it possible to clone these as well? Since I assume there's no phonemes in these sounds, I'm worried about it affecting the overall quality.

 If it's possible, How much do you think would be fair to Include? 

____
And sorry, while I'm here let me ask another question I've had; Should the training samples be of the same length? (which seem to be 5 seconds long.) what happens if I have samples with varying lengths?

**Comment by yl4579** [comment]
The training sample can be any length because we only use a clip anyway, and making 5 seconds of audio is only for convenience. It also works for laughing, breathing and crying, although the pretrained ASR model needs to be trained on datasets with these things too.
