### ISSUE TITLE
How to train it for my own custom dataset?  

### ISSUE THREAD

**Issue by Hammad-Bangash** [yl4579/StarGANv2-VC#93]
Actually, I want to train it for my own custom dataset.  But it shows problems and does not get trained. Could you please specify what should be the audio properties for my own dataset so that i can train it.
![image](https://github.com/yl4579/StarGANv2-VC/assets/129145452/a5cc34bb-4580-4098-81c3-d2cc609ffc32)
this is the problem it shows while training:
![image](https://github.com/yl4579/StarGANv2-VC/assets/129145452/8951a8c8-79ee-4366-ba8e-9385cedc3f7e)

**Comment by yl4579** [comment]
This is likely caused by wrong `num_domain` here: https://github.com/yl4579/StarGANv2-VC/blob/main/Configs/config.yml#L28 (and also your speaker id in the dataset).

**Comment by psvlnandu** [comment]
Hi, since you tried training on your own dataset. can you help me with same? This is really important to me.
