### ISSUE TITLE
Combining Multiple Styles

### ISSUE THREAD

**Issue by SoshyHayami** [yl4579/StarGANv2-VC#94]
As the title says, I'm curios to know if there's a way to combine or average the style of multiple speakers to synthesize a new target style? how do you think it should be implemented if it's possible to do so?

**Comment by yl4579** [comment]
You can just do convex combinations of different styles. The style space is roughly a sphere so it is convex, so any convex combination of N styles is still a style and it represents some speakers as a combination of other speakers.
