### ISSUE TITLE
Question regarding parameter update and evaluation

### ISSUE THREAD

**Issue by paul-reu** [yl4579/StarGANv2-VC#95]
Thank you very much for providing the code!
I have two questions, you can maybe help me with:

1)  After computing the generator loss with a target reference, why is the style_encoder not updated and only the generator (trainer.py, line 218)? It is the same in the original StarGanV2 repository, but could you maybe explain why? 

2) The evaluation is done for trainer.model and not trainer.model_ema, but in the inference example script you load params["model_ema"]. Is it expected to perform better?

Thanks! :)

**Comment by yl4579** [comment]
For 1, please see #14 
For 2, EMA is a technique to average GAN’s weight for stability: https://openreview.net/forum?id=SJgw_sRqFQ, so you only need it during inference.

**Comment by paul-reu** [comment]
Thanks! One more question: The output of the F0 network is F0, GAN_F0 and cyc_F0. What it the reason for using cyc_F0 in the cycle consistency loss and GAN_F0 in the style diversification loss?
